insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (1, 'American Health Packaging', '012 Redwing Parkway', 495050, 'fmcmechan0@deviantart.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (2, 'Mylan Institutional Inc.', '528 Clemons Parkway', 756099, 'gcharrett1@census.gov');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (3, 'YBK Investment, INC', '20532 Corben Park', 833966, 'cshimman2@a8.net');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (4, 'Wal-Mart Stores Inc', '32 Algoma Center', 507704, 'jdrinkale3@kickstarter.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (5, 'Sanofi-Aventis U.S. LLC', '5 Huxley Trail', 502891, 'ncurrao4@deliciousdays.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (6, 'Newton Laboratories, Inc.', '277 Onsgard Center', 470439, 'mbalfre5@globo.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (7, 'Qualitest Pharmaceuticals', '69 Coleman Court', 616380, 'dreyburn6@spiegel.de');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (8, 'REMEDYREPACK INC.', '1 Westerfield Park', 606626, 'mwinship7@archive.org');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (9, 'CVS Pharmacy', '6516 Tennessee Avenue', 528927, 'afilipiak8@scientificamerican.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (10, 'PD-Rx Pharmaceuticals, Inc.', '9 Hauk Avenue', 835862, 'twalliker9@scribd.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (11, 'DAVA Pharmaceuticals, Inc.', '39 Commercial Center', 380000, 'aseera@deliciousdays.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (12, 'Rhodes Pharmaceuticals L.P.', '9151 South Trail', 362011, 'mgabrielb@dailymail.co.uk');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (13, 'Sandoz Inc', '61 Talisman Pass', 942301, 'ctreenc@naver.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (14, 'Wegmans Food Markets Inc.', '41080 Lighthouse Bay Circle', 589973, 'lreolfid@unesco.org');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (15, 'Fleming County Hospital Home Medical Equipment', '072 Petterle Park', 853240, 'hashplante@stanford.edu');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (16, 'Shire US Manufacturing Inc.', '9653 Stone Corner Circle', 752721, 'welgeef@stanford.edu');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (17, 'ALK-Abello, Inc.', '082 Morningstar Way', 126129, 'ateeseg@chicagotribune.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (18, 'Cardinal Health', '9 Northview Hill', 429786, 'fochterlonyh@mit.edu');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (19, 'STAT Rx USA LLC', '506 Hoffman Plaza', 214534, 'cmcdermidi@123-reg.co.uk');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (20, 'Sam''s West Inc', '2 Oak Valley Place', 928544, 'cwitherbedj@delicious.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (21, 'HyVee Inc', '69559 Utah Place', 618556, 'jvanyakink@hc360.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (22, 'Fenwal, Inc.', '5 Vahlen Street', 827964, 'doverill@uol.com.br');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (23, 'Sandoz Inc.', '721 Autumn Leaf Lane', 963662, 'hworralm@hc360.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (24, 'Merck Sharp & Dohme Corp.', '470 Randy Circle', 334699, 'ncappern@upenn.edu');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (25, 'Genzyme Corporation', '7 Hovde Trail', 675081, 'bdallandero@dell.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (26, 'Jubilant HollisterStier LLC', '7 Bellgrove Trail', 258827, 'dsamberp@uiuc.edu');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (27, 'Donovan Industries, Inc.', '22 West Hill', 335189, 'cduckerinq@usgs.gov');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (28, 'US Nonwovens', '74 South Court', 133424, 'mliddyr@sakura.ne.jp');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (29, 'Raritan Pharmaceuticals Inc', '47 Hanson Crossing', 976162, 'ilaskeys@mapquest.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (30, 'Physicians Science & Nature Inc.', '374 Canary Terrace', 402535, 'rwinscombt@irs.gov');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (31, 'Rebel Distributors Corp', '0898 Continental Hill', 794980, 'fkaubleu@mapy.cz');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (32, 'Bare Escentuals Beauty, Inc.', '731 Stang Avenue', 411047, 'ddefontv@google.fr');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (33, 'Bryant Ranch Prepack', '17252 Helena Avenue', 956616, 'dlassellsw@arstechnica.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (34, 'Proficient Rx LP', '3754 Springview Road', 470585, 'grandsx@si.edu');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (35, 'Insight Pharmaceuticals', '72046 Ryan Street', 419916, 'aroydony@elegantthemes.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (36, 'Wal-Mart Stores Inc', '459 Nobel Junction', 430396, 'ppressmanz@google.ru');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (37, 'Covis Pharmaceuticals, Inc.', '65 Katie Place', 177793, 'dsmooth10@google.co.jp');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (38, 'Nelco Laboratories, Inc.', '8 Onsgard Plaza', 819962, 'igribbin11@imdb.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (39, 'HOMEOLAB USA INC.', '3993 Grasskamp Avenue', 825451, 'mettles12@ocn.ne.jp');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (40, 'Accord Healthcare Inc.', '85 Pine View Crossing', 403305, 'estickens13@about.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (41, 'Kroger Company', '30358 Shoshone Court', 385511, 'edownage14@google.ca');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (42, 'Amneal-Agila, LLC', '5 Sunbrook Street', 486846, 'denriques15@tamu.edu');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (43, 'Topco Associates LLC', '6 Lakewood Gardens Point', 663704, 'mconnett16@globo.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (44, 'Aptalis Pharma US, Inc.', '674 Hintze Road', 573190, 'thamelyn17@dailymotion.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (45, 'Physicians Total Care, Inc.', '53 Ilene Lane', 478585, 'abullus18@oracle.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (46, 'Blenheim Pharmacal, Inc.', '037 Bluestem Hill', 343006, 'lgolden19@miitbeian.gov.cn');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (47, 'Natures Way Holding Co.', '66711 Packers Pass', 217915, 'fjeannaud1a@theglobeandmail.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (48, 'ALK-Abello, Inc.', '384 Stang Trail', 277064, 'bferenczy1b@bing.com');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (49, 'Patriot Pharmaceuticals, LLC', '50 Village Green Trail', 109669, 'rbernhardt1c@ebay.co.uk');
insert into Dobavljac (SifraDobavljaca, Ime, Adresa, BrTel, Email) values (50, 'RITE AID CORPORATION', '9445 Columbus Way', 275774, 'pturfes1d@hhs.gov');
