insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Mushroom - Lg - Cello', 'kom', 'neque duis bibendum', 847);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Rum - Dark, Bacardi, Black', 'kom', 'magnis dis', 907);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Fireball Whisky', 'kom', 'donec diam neque', 332);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Sauce - Chili', 'kom', 'cubilia curae mauris', 843);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Water - Spring Water, 355 Ml', 'kom', 'vel dapibus at', 950);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Juice - Clam, 46 Oz', 'kom', 'lorem ipsum dolor sit amet', 461);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Juice - Cranberry, 341 Ml', 'kom', 'pellentesque eget', 576);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Bread - Kimel Stick Poly', 'kom', 'justo sollicitudin ut', 533);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Pail - 4l White, With Handle', 'kom', 'integer a nibh in', 396);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Corn Syrup', 'kom', 'quisque porta volutpat', 544);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Sauce - Demi Glace', 'kom', 'luctus cum sociis natoque penatibus', 622);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Arctic Char - Fillets', 'kom', 'erat id mauris vulputate', 245);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Pastry - Chocolate Chip Muffin', 'kom', 'massa id lobortis convallis', 689);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Anchovy Paste - 56 G Tube', 'kom', 'molestie nibh in', 347);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Tart Shells - Savory, 3', 'kom', 'purus aliquet at feugiat non', 406);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Wine - Niagara Peninsula Vqa', 'kom', 'ipsum praesent blandit', 194);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Quail - Eggs, Fresh', 'kom', 'ut suscipit a feugiat', 115);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Soup - Campbells Asian Noodle', 'kom', 'orci luctus et ultrices', 121);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Tart Shells - Savory, 4', 'kom', 'nulla pede', 658);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Wine - Pinot Noir Latour', 'kom', 'iaculis diam erat', 209);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Grapes - Black', 'kom', 'enim leo rhoncus sed', 466);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Pastry - Raisin Muffin - Mini', 'kom', 'quis lectus', 282);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Wine - Savigny - Les - Beaune', 'kom', 'suspendisse potenti nullam porttitor', 294);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Carbonated Water - Orange', 'kom', 'ac nulla sed', 432);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Towel Multifold', 'kom', 'varius ut', 678);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Beef - Outside, Round', 'kom', 'varius nulla facilisi cras', 766);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Bandage - Flexible Neon', 'kom', 'a odio in', 320);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Oil - Shortening,liqud, Fry', 'kom', 'eu felis fusce', 208);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Foil Wrap', 'kom', 'est quam pharetra magna', 993);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Beer - Upper Canada Lager', 'kom', 'scelerisque mauris', 583);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Seabream Whole Farmed', 'kom', 'hac habitasse platea dictumst', 764);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Trueblue - Blueberry 12x473ml', 'kom', 'sed ante', 968);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Potatoes - Purple, Organic', 'kom', 'nisl ut volutpat', 519);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Boogies', 'kom', 'lectus in', 837);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Potatoes - Fingerling 4 Oz', 'kom', 'sed nisl nunc', 726);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Wine - Duboeuf Beaujolais', 'kom', 'cum sociis natoque penatibus', 831);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Cheese - Le Cheve Noir', 'kom', 'potenti nullam porttitor lacus', 838);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Pork - Tenderloin, Fresh', 'kom', 'odio consequat varius integer ac', 850);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Triple Sec - Mcguinness', 'kom', 'morbi vel lectus', 577);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Peach - Fresh', 'kom', 'arcu libero', 525);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Bagelers - Cinn / Brown', 'kom', 'velit donec diam', 451);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Bag - Bread, White, Plain', 'kom', 'a libero nam dui proin', 837);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Onions - Cippolini', 'kom', 'fermentum donec ut', 890);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Foam Cup 6 Oz', 'kom', 'duis faucibus accumsan odio curabitur', 203);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Soup - Campbells Beef Strogonoff', 'kom', 'nibh in hac habitasse platea', 296);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Schnappes - Peach, Walkers', 'kom', 'sapien ut nunc vestibulum ante', 868);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Fudge - Cream Fudge', 'kom', 'massa id nisl venenatis lacinia', 732);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Roe - Flying Fish', 'kom', 'mi sit amet lobortis sapien', 515);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Creamers - 10%', 'kom', 'sed augue aliquam erat volutpat', 824);
insert into ARTIKAL (NAZIVARTIKLA, JEDINICAMERE, OPISARTIKLA, cena) values ('Cheese - Mozzarella, Shredded', 'kom', 'ante nulla justo aliquam quis', 886);
