insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 79, 18, 50, 'sagittis nam');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 22, 20, 8, 'vestibulum velit id pretium');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 21, 5, 14, 'sed vestibulum');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 35, 3, 3, 'justo pellentesque');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 79, 9, 35, 'dolor sit');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 77, 15, 35, 'nulla tellus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 34, 6, 46, 'aliquam non mauris morbi');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 20, 18, 19, 'eget semper rutrum');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 79, 18, 45, 'orci eget orci');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 65, 20, 40, 'nisi volutpat');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 7, 11, 39, 'justo morbi');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 37, 16, 2, 'lacinia erat');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 57, 3, 2, 'rutrum nulla tellus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 59, 3, 48, 'rutrum neque aenean');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 36, 4, 47, 'interdum mauris ullamcorper');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 46, 20, 48, 'lacus at turpis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 30, 10, 17, 'quam turpis adipiscing lorem');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 95, 3, 2, 'nulla pede');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 96, 7, 42, 'ultrices posuere');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 51, 9, 36, 'luctus nec');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 2, 14, 17, 'vehicula condimentum curabitur');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 16, 17, 43, 'parturient montes nascetur ridiculus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 38, 15, 9, 'potenti cras');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 16, 11, 38, 'ridiculus mus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 85, 20, 47, 'accumsan felis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 29, 10, 27, 'vitae quam suspendisse potenti');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 32, 7, 14, 'duis aliquam convallis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 93, 19, 10, 'quam fringilla rhoncus mauris');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 13, 15, 6, 'risus auctor');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 93, 4, 24, 'porttitor pede');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 34, 12, 13, 'odio condimentum');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 4, 10, 16, 'euismod scelerisque quam turpis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 7, 11, 44, 'consequat lectus in');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 23, 12, 31, 'donec pharetra');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 31, 14, 38, 'odio odio elementum');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 52, 10, 49, 'hac habitasse platea');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 67, 3, 48, 'rutrum ac');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 72, 1, 29, 'tempus vel');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 86, 18, 38, 'ullamcorper augue a suscipit');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 9, 10, 33, 'tempus sit amet sem');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 2, 19, 16, 'non quam nec');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 33, 13, 14, 'sapien a');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 92, 3, 13, 'at ipsum ac');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 78, 3, 7, 'consequat ut nulla sed');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 77, 16, 5, 'morbi non lectus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 93, 16, 35, 'orci eget orci vehicula');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 78, 10, 19, 'interdum eu tincidunt in');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 33, 10, 19, 'justo lacinia');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 63, 16, 18, 'ipsum integer a nibh');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 54, 9, 50, 'blandit mi in');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 86, 11, 18, 'semper sapien a');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 48, 18, 24, 'risus auctor');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 34, 8, 32, 'at nibh');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 26, 11, 50, 'magnis dis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 30, 17, 37, 'in eleifend quam');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 2, 10, 49, 'vestibulum proin eu');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 86, 15, 22, 'rutrum nulla nunc purus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 7, 12, 4, 'interdum eu');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 65, 2, 3, 'pede ullamcorper');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 60, 8, 30, 'sodales scelerisque');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 63, 9, 14, 'non mauris morbi non');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 35, 6, 6, 'magna vulputate');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 31, 18, 9, 'consequat lectus in est');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 100, 5, 30, 'nulla ac enim');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 84, 12, 50, 'leo maecenas pulvinar lobortis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 3, 18, 31, 'ut volutpat sapien arcu');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 99, 18, 26, 'ac nibh fusce');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 65, 9, 46, 'ridiculus mus vivamus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 31, 4, 24, 'viverra pede ac diam');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 94, 7, 41, 'erat vestibulum sed magna');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 70, 11, 15, 'elit proin risus praesent');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 99, 9, 28, 'vestibulum ante ipsum');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 73, 2, 29, 'luctus rutrum nulla');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 33, 13, 7, 'est donec odio justo');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 45, 15, 1, 'id ligula suspendisse');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 66, 3, 44, 'eget tincidunt eget');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 58, 8, 41, 'augue quam sollicitudin');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 14, 8, 42, 'faucibus cursus urna');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 76, 2, 13, 'suspendisse potenti');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 66, 14, 41, 'lectus in');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 66, 17, 46, 'hac habitasse');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 58, 8, 40, 'luctus et');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 54, 14, 7, 'sed accumsan felis ut');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 49, 14, 6, 'libero ut massa');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 42, 6, 33, 'sed accumsan felis ut');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 78, 19, 9, 'morbi non quam nec');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 58, 16, 17, 'cum sociis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 95, 4, 42, 'lacus morbi sem mauris');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 39, 10, 3, 'enim in tempor');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 33, 13, 6, 'justo etiam pretium iaculis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 91, 3, 45, 'suscipit a feugiat');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 17, 15, 37, 'nec nisi volutpat eleifend');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 90, 13, 32, 'adipiscing elit');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 1, 1, 34, 'nisi venenatis');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 65, 8, 33, 'justo in blandit');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 36, 7, 40, 'ante ipsum primis in');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (2, 65, 13, 15, 'eros elementum pellentesque');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 52, 14, 20, 'in faucibus orci luctus');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (3, 20, 7, 3, 'lacus curabitur');
insert into StavkaOtpremnice (Rbr, Kolicina, BrOtpremnice, SifraArtikla, Napomena) values (1, 38, 17, 35, 'in felis eu');
