insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 34, 13, 'ut mauris', 22);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 75, 10, 'sed accumsan felis', 37);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 48, 3, 'platea dictumst etiam', 28);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 59, 14, 'dictumst etiam faucibus', 2);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 94, 16, 'eu massa donec', 1);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 92, 17, 'est congue', 18);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 49, 2, 'pede ac diam', 47);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 73, 8, 'leo pellentesque', 26);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 47, 10, 'pellentesque volutpat dui', 38);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 61, 13, 'molestie nibh', 50);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 88, 11, 'sit amet', 36);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 94, 9, 'blandit lacinia', 8);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 50, 1, 'bibendum felis', 5);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 73, 6, 'neque libero', 50);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 54, 12, 'elementum pellentesque', 27);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 57, 5, 'rhoncus aliquam', 30);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 46, 4, 'at nulla', 9);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 50, 11, 'ipsum primis', 19);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 90, 14, 'sapien a libero', 25);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 52, 7, 'turpis sed', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 85, 14, 'vestibulum eget', 32);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 48, 13, 'ut erat id', 20);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 31, 20, 'pede lobortis', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 69, 8, 'vel nulla', 17);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 56, 3, 'dapibus at', 16);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 77, 9, 'odio condimentum', 3);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 90, 6, 'leo odio', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 53, 4, 'nullam varius nulla', 36);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 21, 3, 'mi nulla ac', 39);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 92, 20, 'dui luctus rutrum', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 31, 16, 'sapien a libero', 12);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 58, 19, 'id consequat', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 12, 11, 'nulla pede ullamcorper', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 21, 17, 'sit amet erat', 35);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 75, 2, 'pede libero quis', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 96, 19, 'dui proin leo', 48);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 65, 1, 'tortor risus dapibus', 1);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 37, 4, 'ac enim in', 5);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 33, 14, 'lacus morbi', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 94, 6, 'odio in hac', 10);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 42, 11, 'vel ipsum praesent', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 70, 6, 'venenatis non', 32);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 9, 17, 'augue vestibulum rutrum', 48);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 85, 20, 'id ligula', 4);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 38, 20, 'felis ut', 2);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 46, 9, 'erat id', 8);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 10, 10, 'orci mauris lacinia', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 28, 16, 'interdum mauris', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 67, 3, 'integer ac leo', 21);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 17, 1, 'tempus vivamus', 28);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 80, 2, 'mi integer', 36);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 19, 4, 'varius ut', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 60, 6, 'lorem quisque', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 87, 4, 'ullamcorper augue a', 9);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 39, 6, 'in congue etiam', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 88, 9, 'aliquet ultrices erat', 36);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 68, 14, 'purus eu', 18);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 71, 16, 'cursus vestibulum proin', 3);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 16, 1, 'purus sit', 6);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 32, 14, 'sed ante', 9);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 90, 15, 'sit amet', 2);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 47, 18, 'et magnis', 17);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 80, 14, 'ultrices phasellus', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 58, 14, 'pellentesque volutpat', 11);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 57, 15, 'non velit donec', 37);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 15, 2, 'venenatis non sodales', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 34, 10, 'consequat morbi', 23);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 23, 8, 'ut suscipit', 6);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 86, 2, 'nullam varius nulla', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 2, 18, 'luctus et ultrices', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 43, 14, 'luctus et', 50);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 85, 9, 'pretium nisl ut', 31);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 72, 16, 'ut at dolor', 43);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 85, 14, 'sapien quis libero', 9);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 8, 14, 'nam dui', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 79, 20, 'nullam molestie nibh', 14);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 60, 14, 'ridiculus mus', 43);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 50, 10, 'vestibulum proin eu', 20);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 32, 5, 'at vulputate vitae', 25);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 39, 11, 'libero non mattis', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 10, 20, 'erat curabitur', 42);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 26, 20, 'fusce lacus purus', 39);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 100, 3, 'nec euismod', 42);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 85, 14, 'curabitur convallis', 28);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 55, 16, 'accumsan felis ut', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 87, 16, 'interdum mauris ullamcorper', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 53, 2, 'amet nunc viverra', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 66, 13, 'in est risus', 47);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 64, 12, 'sapien placerat', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 31, 6, 'ut nunc', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 12, 16, 'nam nulla integer', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 77, 18, 'nec sem duis', 3);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 81, 8, 'ultrices posuere cubilia', 31);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 14, 9, 'sapien quis', 47);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 16, 13, 'eu pede', 8);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 74, 4, 'lobortis est', 12);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 7, 17, 'nam dui', 11);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 94, 19, 'sed nisl', 23);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 46, 3, 'sapien urna pretium', 3);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 11, 13, 'condimentum id', 16);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 26, 15, 'nulla ut', 12);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 96, 6, 'risus dapibus', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 98, 6, 'adipiscing elit', 8);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 58, 19, 'ipsum integer', 45);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 66, 8, 'nisi venenatis', 45);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 3, 15, 'ut ultrices', 39);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 13, 4, 'vivamus vestibulum sagittis', 24);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 92, 18, 'eget congue eget', 26);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 10, 8, 'sed tincidunt eu', 26);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 64, 9, 'pellentesque ultrices', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 57, 11, 'quis justo maecenas', 28);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 93, 18, 'donec semper', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 27, 13, 'pretium iaculis diam', 29);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 38, 19, 'metus sapien ut', 22);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 51, 4, 'adipiscing elit proin', 12);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 70, 2, 'blandit ultrices', 28);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 95, 11, 'ullamcorper augue', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 34, 6, 'interdum mauris non', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 36, 12, 'sed justo', 30);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 46, 20, 'maecenas ut massa', 22);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 58, 1, 'rhoncus aliquam', 5);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 88, 14, 'pede justo lacinia', 26);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 31, 17, 'rhoncus aliquam', 48);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 62, 9, 'eget eros', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 80, 8, 'aliquam non mauris', 25);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 37, 10, 'commodo placerat praesent', 32);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 66, 9, 'consequat morbi', 4);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 43, 13, 'donec diam', 38);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 27, 20, 'praesent id', 23);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 82, 18, 'ornare consequat lectus', 32);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 91, 18, 'luctus tincidunt', 43);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 20, 17, 'quisque ut', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 76, 13, 'purus sit amet', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 87, 19, 'vel accumsan', 29);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 45, 8, 'elementum in hac', 16);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 82, 7, 'a ipsum', 20);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 22, 17, 'lorem ipsum', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 98, 8, 'integer tincidunt ante', 9);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 5, 12, 'ut massa', 12);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 99, 20, 'blandit lacinia', 37);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 54, 11, 'blandit lacinia', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 60, 7, 'magnis dis parturient', 19);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 62, 16, 'massa id nisl', 32);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 23, 6, 'diam nam tristique', 6);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 19, 18, 'bibendum imperdiet nullam', 27);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 62, 14, 'sem mauris', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 7, 4, 'in hac habitasse', 14);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 28, 17, 'leo maecenas', 27);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 47, 8, 'nulla suscipit ligula', 25);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 34, 8, 'ultrices posuere', 30);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 99, 1, 'tincidunt eget', 34);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 41, 10, 'ante ipsum primis', 11);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 95, 14, 'mauris sit amet', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 100, 7, 'turpis sed', 29);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 32, 9, 'habitasse platea dictumst', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 91, 13, 'quis turpis sed', 37);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 43, 9, 'risus dapibus augue', 36);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 78, 3, 'etiam faucibus', 45);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 33, 16, 'odio cras mi', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 96, 6, 'nulla nunc purus', 1);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 49, 11, 'luctus tincidunt', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 23, 6, 'maecenas leo odio', 1);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 94, 1, 'in magna bibendum', 8);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 62, 10, 'duis at velit', 10);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 59, 20, 'fermentum donec', 40);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 60, 1, 'in sagittis', 22);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 19, 1, 'vulputate justo', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 85, 12, 'phasellus in felis', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 63, 7, 'rutrum at', 11);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 4, 15, 'interdum in ante', 50);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 11, 18, 'augue vel accumsan', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 42, 17, 'nisi at', 45);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 20, 19, 'nulla nisl nunc', 29);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 14, 9, 'vestibulum ante', 24);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 29, 13, 'sociis natoque', 42);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 26, 7, 'interdum venenatis', 39);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 77, 2, 'curabitur gravida', 31);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 24, 1, 'erat tortor sollicitudin', 22);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 2, 14, 'morbi vestibulum', 30);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 42, 16, 'fusce posuere', 31);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 50, 2, 'mollis molestie lorem', 17);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 26, 7, 'et ultrices', 24);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 35, 8, 'convallis duis', 10);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 31, 4, 'eu massa donec', 27);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 96, 9, 'turpis elementum ligula', 34);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 1, 3, 'justo in', 42);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 57, 1, 'quam turpis', 45);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 14, 19, 'tempor convallis', 39);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 87, 11, 'blandit non interdum', 34);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 40, 3, 'praesent id', 21);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 15, 18, 'enim lorem', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 81, 10, 'vel ipsum', 43);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 76, 3, 'euismod scelerisque', 12);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 87, 17, 'non mauris morbi', 48);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 42, 2, 'nisl nunc', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 32, 18, 'dolor vel', 1);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 70, 4, 'diam vitae quam', 19);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 21, 1, 'penatibus et magnis', 3);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 41, 20, 'eu massa donec', 5);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 70, 19, 'lectus vestibulum quam', 5);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 84, 6, 'eleifend quam', 21);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 100, 5, 'aliquet at', 19);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 65, 4, 'erat quisque erat', 23);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 79, 5, 'tincidunt eget tempus', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 61, 16, 'sed sagittis', 4);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 13, 8, 'primis in faucibus', 24);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 7, 19, 'vel pede', 16);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 32, 9, 'ridiculus mus', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 12, 14, 'ridiculus mus etiam', 18);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 41, 1, 'eget rutrum at', 8);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 70, 16, 'tristique est et', 23);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 92, 18, 'rhoncus mauris enim', 48);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 18, 4, 'nisi vulputate', 5);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 85, 4, 'fusce congue diam', 47);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 12, 18, 'est donec odio', 34);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 29, 2, 'ut erat id', 26);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 76, 5, 'aliquam convallis', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 55, 4, 'turpis elementum', 27);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 81, 4, 'nulla sed accumsan', 29);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 14, 9, 'vestibulum aliquet ultrices', 45);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 44, 8, 'vel dapibus at', 29);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 65, 6, 'integer pede', 1);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 11, 13, 'pede venenatis', 47);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 86, 2, 'amet consectetuer', 37);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 3, 2, 'quisque ut', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 14, 2, 'et magnis dis', 48);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 98, 6, 'nulla ac', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 75, 14, 'vel augue vestibulum', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 94, 11, 'integer aliquet', 14);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 16, 19, 'rhoncus aliquet pulvinar', 40);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 78, 19, 'interdum in ante', 16);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 100, 11, 'integer non velit', 48);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 8, 10, 'magnis dis', 18);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 1, 16, 'augue a', 10);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 25, 12, 'leo pellentesque', 20);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 23, 9, 'et tempus semper', 2);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 56, 15, 'lacus morbi', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 28, 3, 'donec dapibus', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 25, 16, 'eget massa', 30);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 87, 16, 'massa id', 8);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 76, 15, 'vel lectus', 7);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 98, 3, 'amet nulla quisque', 1);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 16, 11, 'curabitur convallis duis', 24);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 56, 16, 'nulla tempus vivamus', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 91, 14, 'vivamus in', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 70, 12, 'orci luctus', 15);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 24, 7, 'ut suscipit', 39);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 29, 1, 'consequat varius integer', 17);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 54, 2, 'integer ac', 26);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 52, 13, 'nisl duis', 19);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 4, 9, 'eleifend pede', 27);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 2, 13, 'volutpat erat', 37);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 70, 17, 'pellentesque at nulla', 35);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 32, 17, 'aenean lectus pellentesque', 40);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 14, 10, 'ligula sit', 23);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 98, 12, 'diam vitae', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 58, 4, 'ridiculus mus vivamus', 4);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 82, 5, 'curabitur gravida', 24);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 9, 14, 'nisi at nibh', 47);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 39, 9, 'sodales sed', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 61, 1, 'mauris ullamcorper', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 36, 7, 'hac habitasse', 43);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 46, 4, 'vestibulum quam', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 35, 8, 'massa volutpat convallis', 41);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 4, 13, 'lorem id', 44);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 66, 8, 'nisi vulputate nonummy', 40);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 17, 5, 'odio consequat', 18);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 11, 8, 'tortor duis', 25);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 25, 20, 'quam sollicitudin', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 86, 9, 'sem fusce consequat', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 74, 6, 'in blandit', 19);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 60, 19, 'consectetuer adipiscing elit', 47);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 3, 9, 'sapien cum', 2);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 45, 20, 'lacinia erat vestibulum', 27);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 98, 12, 'pellentesque quisque', 49);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 51, 11, 'leo pellentesque', 46);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 65, 13, 'penatibus et', 4);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 78, 4, 'mauris enim leo', 14);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 20, 18, 'sapien non', 25);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 12, 9, 'rhoncus aliquam', 21);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 34, 7, 'rhoncus aliquam lacus', 13);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 14, 20, 'quam fringilla rhoncus', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 54, 17, 'augue vestibulum', 6);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 23, 9, 'praesent lectus', 35);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 37, 10, 'volutpat sapien', 32);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 75, 7, 'montes nascetur ridiculus', 25);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 67, 16, 'massa volutpat', 23);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 87, 1, 'duis ac nibh', 19);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 97, 16, 'volutpat in congue', 33);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 82, 20, 'rutrum nulla tellus', 37);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 96, 18, 'ornare imperdiet', 17);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 96, 5, 'consectetuer eget rutrum', 18);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 57, 6, 'lorem ipsum dolor', 18);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 100, 20, 'scelerisque quam turpis', 30);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 51, 20, 'nullam molestie', 34);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 34, 13, 'parturient montes', 42);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 14, 18, 'vel sem', 26);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (1, 14, 20, 'sit amet cursus', 42);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (2, 73, 11, 'semper sapien', 21);
insert into StavkaUpita (Rbr, Kolicina, SifraUpita, Napomena, SifraArtikla) values (3, 15, 9, 'non ligula pellentesque', 18);
